#!/bin/sh

################################################################################
#                               git-init-www
#
# git-init-www set up a bare repo at '/home/<user>/www.git' to deploy to 
# '/home/<user>/public_html' whenever there is a push
#
# Requirements:
# - Centos 6.x (tested on centos 6)
# - Git
#
# ** Set this script as executable: 
# > chmod +x git-init-www
#
# ** Execute
# ./git-init-www <user>
#
# Push to our repo with shh
# > git remote add origin ssh://user@domain/home/<user>/www.git
# > git push origin master
#
# @author: Mardix <http://github.com/mardix>
# @Since: Nov 17 2012
#
# Version: 1.1 (Dec 9 2012)
################################################################################

usage(){
echo "
USAGE: ./git-init-www <user>
"
}

if [ -z "$1" ]; then
    usage
    exit;
fi


USER_HOME="/home/$1"
PUBLIC_DIR="$USER_HOME/public_html"
BARE_REPO="$USER_HOME/www.git"

if [ ! -d "$USER_HOME" ]; then
        echo "Directory: '$USER_HOME' doesn't exist"
        exit
fi

if [ ! -d "$BARE_REPO" ]; then
        mkdir "$BARE_REPO"
        cd "$BARE_REPO"
        git init --bare

        if [ ! -f "hooks/post-receive" ]; then

        echo "
        #!/bin/sh
        GIT_WORK_TREE=$PUBLIC_DIR git checkout -f

        " > hooks/post-receive
        chmod +x hooks/post-receive
        fi
fi

echo "Done!"
